# Generated by Django 3.2.4 on 2021-07-10 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opp', models.CharField(max_length=100)),
                ('championship', models.CharField(choices=[('L', 'League Game'), ('C', 'Cup Game'), ('E', 'European Game')], default='L', max_length=1)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.team')),
            ],
        ),
    ]
